sorting:
  # Possible values: extension, name, time, size, version
  column: name
  reverse: false
  # Whether to group directories together and where.
  # When "classic" is set, this is set to "none".
  # Possible values: first, last, none
  dir-grouping: first

color:
  theme: custom
